name: "Digital Marketing Specialist"
description: "A digial marketing specialist agency in Wiltshire, England."

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: /:title/
highlighter: pygments

# RSS info
author: Tom Davenport
copyright: Digital Marketing Specialist Ltd
