name: "Digital Marketing Specialist"
description: "A top-rated digial marketing specialist in Wiltshire, England. Book your free consultation with our expert team today."

#url: "http://www.digitalmarketingspecialist.co.uk"
#url: "http://192.168.1.191:4000"
url: "//localhost:4000"


paginate: 10

# markdown: rdiscount
permalink: /:title/
highlighter: pygments

# RSS info
author: Tom Davenport
copyright: Digital Marketing Specialist Ltd
twitter: dms_tweets

gems:
#- jekyll-sitemap
- jekyll-redirect-from
# - ruby-oembed
- jekyll-paginate

#sitemap:
#    file: "/sitemap.xml"
#    exclude:
#		- "/rss.xml"
#		- "/privacy-policy.html
#    include_posts:
#        - "/index.html"
#    change_frequency_name: "change_frequency"
#    priority_name: "priority"

include: [.htaccess]

exclude: [node_modules, docs, .gitignore, Gemfile, Gemfile.lock, gulpfile.js, package.json, npm-debug.log]

timezone: Europe/London