name: "Digital Marketing Specialist"
description: "A digial marketing specialist agency in Wiltshire, England."

url: "http://www.digitalmarketingspecialist.co.uk"
#url: "http://localhost:4000"

paginate: 10

# markdown: rdiscount
permalink: /:title/
highlighter: pygments

# RSS info
author: Tom Davenport
copyright: Digital Marketing Specialist Ltd
twitter: tomdavenport

# Sitemap

gems:
#- jekyll-sitemap
- jekyll-redirect-from
# - ruby-oembed
- jekyll-paginate

#sitemap:
#    file: "/sitemap.xml"
#    exclude:
#		- "/rss.xml"
#		- "/privacy-policy.html
#    include_posts:
#        - "/index.html"
#    change_frequency_name: "change_frequency"
#    priority_name: "priority"

exclude: [node_modules, docs, .gitignore, Gemfile, Gemfile.lock, gulpfile.js, package.json]