Google Adwords:

  benefit1: Increase traffic
  benefit2: Higher conversion rate
  benefit3: Measure ROI

  cta: Setup Now


  cta2:

  clientBanner:

  certification: content-marketing-certified.png
  certificationdescription: Content Marketing Specialist certified badge


  price1: £250
  tier1: Start up your digital marketing machine.

  price2: £250/month
  tier2: Improve your advertising ROI with monthly profit management.

  price 3: £99
  tier3: Add a new campaign anytime for a simple fixed fee.